# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 113f8f881f00267d92157851d72fb6f9e220340424908bbb5e9e1c8e6955cde7e1d850326a96660bf5e5870c201509f3aaa308f4e620ce2f8e27dceb3915e721

test:
  secret_key_base: 8d18984965b9a18f6968803214668668f4469c4e3f76db22dd11c544ff8a9938eba0a52cb6f73b3b8dc1984e27eb0dcbed26ad423d63c3b0514f47970103ed32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
